__include__: [
  '../../../dataset/custom_detection.yml',
  '../../../runtime.yml',
  '../../include/dataloader.yml',
  '../../include/optimizer.yml',
  '../../include/dfine_hgnetv2_bifpn_hybrid.yml',
]

output_dir: ./output/dfine_hgnetv2_m_obj2custom

DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True
  pretrained: False

DFINETransformer:
  num_layers: 4  # 5 6
  eval_idx: -1  # -2 -3

HybridBiFPNEncoder:  
  in_channels: [384, 768, 1536]  # Keep the same in_channels as the original  
  hidden_dim: 256  
  depth_mult: 1.0  # Increase from 0.67  
  expansion: 1.5   # Increase from 1.0  
  num_bifpn_blocks: 5  # Increase from 3

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00000625
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00000625
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0000625
  betas: [0.9, 0.999]
  weight_decay: 0.000125


epochs: 46 # Early stop
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 500
  collate_fn:
    stop_epoch: 500
    base_size_repeat: 20

checkpoint_freq: 1
print_freq: 1000

