__include__: [
  '../../../dataset/custom_detection.yml',
  '../../../runtime.yml',
  '../../include/dataloader.yml',
  '../../include/optimizer.yml',
  '../../include/dfine_hgnetv2_hsfpn.yml',
]

output_dir: ./output/dfine_hgnetv2_m_obj2custom

DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True
  pretrained: False

DFINETransformer:
  num_layers: 4  # 5 6
  eval_idx: -1  # -2 -3

HybridHSFPNEncoder:
  in_channels: [384, 768, 1536]  # Already correct  
  feat_strides: [8, 16, 32]      # Add this  
  hidden_dim: 256                # Already correct  
  use_encoder_idx: [2]           # Add this  
  dim_feedforward: 1024          # Update this  
  dropout: 0.0                   # Add this  
  enc_act: 'gelu'                # Add this  
  num_encoder_layers: 1          # Add this  
  pe_temperature: 10000          # Add this  
  depth_mult: 0.67               # Already correct  
  eval_spatial_size: [320, 320]  # Add this to match your input size  
  use_hsfpn: True                # Add this

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00000625
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00000625
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0000625
  betas: [0.9, 0.999]
  weight_decay: 0.000125


epochs: 46 # Early stop
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 500
  collate_fn:
    stop_epoch: 500
    base_size_repeat: 20

checkpoint_freq: 1
print_freq: 1000