__include__: [
  '../../../dataset/custom_detection.yml',
  '../../../runtime.yml',
  '../../include/dataloader.yml',
  '../../include/optimizer.yml',
  '../../include/dfine_hgnetv2.yml',
]

output_dir: ./output/dfine_hgnetv2_m_obj2custom

DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True
  pretrained: False

DFINETransformer:
  num_layers: 4  # 5 6
  eval_idx: -1  # -2 -3

BiFPNEncoder:  
  in_channels: [384, 768, 1536]  # Keep the same input channels from HGNetv2-B2  
  hidden_dim: 256  # Start with the same as your current config  
  num_bifpn_layers: 4  # More layers for better feature fusion  
  weighted_fusion: True  # Enable weighted feature fusion  
  attention_type: "spatial"  # Add spatial attention to focus on distorted regions

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00000625
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00000625
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0000625
  betas: [0.9, 0.999]
  weight_decay: 0.000125


epochs: 46 # Early stop
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 500
  collate_fn:
    stop_epoch: 500
    base_size_repeat: 20

checkpoint_freq: 1
print_freq: 1000

