__include__: [
  './dfine_hgnetv2_s_coco.yml',
  '../base/deim.yml'
]

output_dir: ./outputs/deim_hgnetv2_s_coco

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.0001
    - 
      params: '^(?=.*(?:norm|bn)).*$'     # except bias
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001


# Increase to search for the optimal ema
epoches: 50 # 120 + 4n

## Our LR-Scheduler
flat_epoch: 30    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 3

## Our DataAug
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [3, 3, 47]   # list 
        ops: ['Mosaic', 'RandomAffine']
        mosaic_prob: 0.0
  collate_fn:
    mixup_prob: 0.0
    mixup_epochs: [4, 29]
    stop_epoch: 50    # epoch in [72, ~) stop `multiscales`