train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomFisheyeShiftCrop, max_shift: 0.25, crop_ratio: 0.85, p: 0.7}
        - {type: FisheyeEdgeStretchCrop, stretch_prob: 0.5, scale_y: 0.9}
        - {type: RandomAffine, degrees: 0, translate: [0.05, 0.05], scale: [0.9, 1.1], shear: [0, 0]}
        - {type: RandomHorizontalFlip} 
        - {type: SanitizeBoundingBoxes, min_size: 1}  # Before resize
        - {type: Resize, size: [960, 960]}  # Slightly bigger helps tiny objects
        - {type: SanitizeBoundingBoxes, min_size: 2}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 72
        ops: ['RandomPhotometricDistort', 'RandomFisheyeShiftCrop', 'FisheyeEdgeStretchCrop']

  collate_fn:
    type: BatchImageCollateFunction
    base_size: 960
    base_size_repeat: 3
    stop_epoch: 72 # epoch in [72, ~) stop `multiscales`

  shuffle: True
  total_batch_size: 8 # total batch size equals to 32 (4 * 8)
  num_workers: 8


val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [960, 960], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  total_batch_size: 16
  num_workers: 8
