
train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomAffine, degrees: 0, translate: [0.1, 0.1], scale: [0.7, 1.3], shear: [0, 0]} 
        - {type: RandomIoUCrop, p: 0.9, min_scale: 0.3}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: RandomRotate90, p: 0.2}  # New: helps with orientation
        - {type: RandomPatchGaussian, p: 0.3}  # New: enhances small objects
        - {type: Resize, size: [960, 960]}
        - {type: SanitizeBoundingBoxes, min_size: 2}  # Increased min size for better quality
        - {type: FilterSmallInstances, min_pixels: 9, min_visibility: 0.2}  # New
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 72 # epoch in [71, ~) stop `ops`
        ops: ['RandomPhotometricDistort', 'RandomAffine', 'RandomIoUCrop', 'RandomRotate90', 'RandomPatchGaussian']

  collate_fn:
    type: BatchImageCollateFunction
    base_size: 960
    base_size_repeat: 3
    stop_epoch: 72 # epoch in [72, ~) stop `multiscales`

  shuffle: True
  total_batch_size: 8 # total batch size equals to 32 (4 * 8)
  num_workers: 8


val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [960, 960], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  total_batch_size: 16
  num_workers: 8
