print_freq: 100
output_dir: './logs'
checkpoint_freq: 5

sync_bn: True
find_unused_parameters: False

use_amp: True
scaler:
  type: GradScaler
  enabled: True

use_ema: False
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000

use_wandb: True
project_name: D-FINE # for wandb
exp_name: baseline # wandb experiment name
